spring.application.name=payments
server.port=8085
spring.datasource.url=jdbc:postgresql://localhost:5435/payments_db
spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=none
spring.datasource.driver-class-name=org.postgresql.Driver

spring.config.import=optional:file:.env[.properties]
stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}


#kafka -producer
spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.template.default-topic=order-completed
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
