services:
  user-postgres:
    image: postgres:latest
    container_name: user_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"

  product-postgres:
    image: postgres:latest
    container_name: product_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: product_db
    ports:
      - "5433:5432"

  mongodb:
    image: mongo:latest
    container_name: cart_db
    environment:
      MONGO_INITDB_DATABASE: cart
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001"