spring.application.name=payments
server.port=8085
spring.datasource.url=jdbc:postgresql://localhost:5435/payments_db
spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

spring.config.import=optional:file:.env[.properties]
stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}
