spring.application.name=order-ingestion-service
server.port=8083

#kafka -producer
spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.template.default-topic=orders
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

#Simulation Configuration
simulation.interval-ms=6000
simulation.ingestion-endpoint=http://localhost:8083/api/v1/ingestion
simulation.requests-per-interval=1000
simulation.parallel-threads=10