spring.application.name=product-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5433/product_db
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none


#Minio
minio.accessKey=minioadmin
minio.secretKey=minioadmin
minio.endpoint=http://localhost:9000
minio.bucket=products

spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.max-file-size=50MB

#spring.docker.compose.services=product-postgres
#spring.docker.compose.enabled=false