spring.application.name=cart-service
server.port=8081

spring.mongodb.port=27017
spring.mongodb.host=localhost
spring.mongodb.representation.uuid=standard

user.service.url=http://localhost:8080/api/v1/user
spring.docker.compose.services=mongodb
spring.docker.compose.enabled=false